### ISSUE TITLE
PaillierPassiveWeight在梯度回传计算时，为何以下部分(follower端传递数据需要和leader端数据对比)

### ISSUE THREAD

**Issue by renjian95** [alibaba/Elastic-Federated-Learning-Solution#14]
dw = x * fixedpoint_encode(dy, decrease_precision=True)
sum_mantissa = dw.mantissa.tensor[0]
sum_exponent = dw.exponent[0]
keypair = dw.mantissa.keypair
cond = lambda i, m, e: tf.less(i, tf.shape(inputs)[0])
def body(i, m, e):
    fp = FixedPointTensor(PaillierTensor(keypair, m), e) + \
         FixedPointTensor(PaillierTensor(keypair, dw.mantissa.tensor[i]), dw.exponent[i])
    m = fp.mantissa.tensor
    e = fp.exponent
    return tf.add(i, 1), m, e
_, m, e = tf.while_loop(cond=cond, body=body, loop_vars=[tf.constant(1), sum_mantissa, sum_exponent])
dw = FixedPointTensor(PaillierTensor(keypair, m), e)

**Comment by JacobiSong** [comment]
这部分并不是在对比数据，而是为了不让leader获取真实的梯度，follower在对数据加噪。同时为了不让噪声影响训练，双方会在每次的前向计算阶段去除以往加入的噪声带来的影响。

**Comment by renjian95** [comment]
这个操作在leader端完成，看起来应该是为了获得dw，也就是loss对W的加密梯度；
同样的逻辑在PaillierPassiveDense是这么实现的：
  fpdy = fixedpoint_encode(dy, decrease_precision=True)
   xt = FixedPointTensor(PaillierTensor(self._keypair, tf.transpose(x_mantissa)), tf.transpose(x_exponent))
   dw = xt @ fpdy

**Comment by renjian95** [comment]
这个操作在leader端完成，看起来应该是为了获得dw，也就是loss对W的加密梯度；
同样的逻辑在PaillierPassiveDense是这么实现的：
fpdy = fixedpoint_encode(dy, decrease_precision=True)
xt = FixedPointTensor(PaillierTensor(self._keypair, tf.transpose(x_mantissa)), tf.transpose(x_exponent))
dw = xt @ fpdy
而在PaillierPassiveWeight中，对计算的dw梯度数据，内部做了一次loop用来做累加；
那么在这个dw计算中，为什么需要完成循环累加呢？

**Comment by JacobiSong** [comment]
这是因为PaillierDense实现的是矩阵乘法Y = X @ W，而在PaillierWeight中是单纯的加权Y = X * w， w不是一个矩阵，而是一个向量，即X的每一行和w做element-wise的乘法。但在求梯度时，X是一个矩阵，dY也是一个矩阵，将X和dY做element-wise的乘法后得到的也是一个矩阵，还需要把每一行累加起来，才能得到dw，又由于这是在密文上做的运算，所以我们无法使用tf.reduce_sum实现。这就是为什么使用loop的原因，
