### ISSUE TITLE
Insecure parameters for paillier

### ISSUE THREAD

**Issue by vincehong** [alibaba/Elastic-Federated-Learning-Solution#4]
https://github.com/alibaba/Elastic-Federated-Learning-Solution/blob/master/efls-train/python/efl/privacy/encrypt.py#L27

According to [NIST's Recommendation for
Key Management](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r5.pdf) , 1024 bit of n only reaches <= 80 bit security, which is no longer considered sufficiently secure.

**Comment by JacobiSong** [comment]
Thank you for your suggestion :)
The bits of n will be 4096 by default in our next update, and it will be coming soon.
The increase of bits of n will lead to the increase of decryption time, and in our testing, decryption time is one of the training bottlenecks, so you may need to find a balance between privacy protection and training efficiency.
